volumes:
  db-data:

networks:
  instavote:
    driver: bridge

services:
  vote:
    image: karthikeyanr/vote:latest
    build: ./vote
    ports:
      - 7000:80
    depends_on:
      - redis
    networks:
      - instavote

  redis:
    image: redis:alpine
    networks:
      - instavote

  db:
    image: postgres:9.4
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - instavote
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  result:
    image: karthikeyanr/result:latest
    build: ./result
    ports:
      - 7001:4000
    depends_on:
      - db
    networks:
      - instavote

  worker:
    image: karthikeyanr/worker:latest
    build: ./worker
    depends_on: 
      - redis
      - db
    networks:
      - instavote
